runtime: python27
threadsafe: false

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.js\.map)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.js\.map)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: static/\1
  upload: static/(.*\.(mid|midi|mp3|wav))  

# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html

- url: /(.+)
  static_files: static/\1/index.html
  upload: static/(.+)/index.html

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html